# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts: !include tts.yaml

group: !include groups.yaml
# automation: !include automations.yaml
automation: !include_dir_merge_list automations/
# script: !include scripts.yaml
script: !include_dir_merge_list scripts/
scene: !include scenes.yaml

lovelace: !include lovelace.yaml

recorder: !include recorder.yaml

homematic: !include homematic.yaml

binary_sensor: !include_dir_merge_list binary_sensors/
device_tracker: !include_dir_merge_list device_trackers/