# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts: !include tts.yaml

group: !include_dir_named groups/
automation: !include_dir_merge_list automations/
script: !include_dir_named scripts/
scene: !include scenes.yaml

light: !include_dir_merge_list lights/

lovelace: !include lovelace.yaml

recorder: !include recorder.yaml

homematic: !include homematic.yaml

binary_sensor: !include_dir_merge_list binary_sensors/
device_tracker: !include_dir_merge_list device_trackers/
input_boolean: !include_dir_merge_list input_booleans/
