# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts: !include tts.yaml

group: !include_dir_named groups/
automation: !include_dir_merge_list automations/
script: !include_dir_named scripts/
scene: !include scenes.yaml

light: !include_dir_merge_list lights/

lovelace: !include lovelace.yaml

recorder: !include recorder.yaml

homematic: !include homematic.yaml

influxdb: !include influxdb.yaml

shelly: !include shelly.yaml

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

apcupsd: !include apcupsd.yaml

fan: !include fan.yaml

spotify: !include spotify.yaml

binary_sensor: !include_dir_merge_list binary_sensors/
device_tracker: !include_dir_merge_list device_trackers/
input_boolean: !include_dir_named input_booleans/
input_datetime: !include_dir_named input_datetimes/
input_number: !include_dir_named input_numbers/
input_select: !include_dir_named input_selects/
input_text: !include_dir_named input_texts/
sensor: !include_dir_merge_list sensors/

homeassistant:
  customize: !include customize.yaml
#     input_boolean.is_visitors_room_occupied:
#       templates:
#         icon: >
#           if (state === 'on') return 'mdi:bell';
#           return 'mdi:bell-off';
#         icon_color: >
#           if (state === 'on') return 'rgb(251, 210, 41)';
#           return 'rgb(54, 95, 140)';
