title: Admin Panel
views:
  - !include lovelace/views/admin/main.yaml
  - !include lovelace/views/admin/healthcheck.yaml
  - !include lovelace/views/admin/kitchen.yaml
  - !include lovelace/views/admin/living_room.yaml
  - !include lovelace/views/admin/office.yaml
  - !include lovelace/views/admin/boiler_house.yaml
  - !include lovelace/views/admin/garage.yaml
  - !include lovelace/views/admin/gameroom.yaml
  - !include lovelace/views/admin/upper_bathroom.yaml
  - !include lovelace/views/admin/toilet.yaml
  - !include lovelace/views/admin/bedroom.yaml
  - !include lovelace/views/admin/kamil_room.yaml
  - !include lovelace/views/admin/visitors_room.yaml
  - !include lovelace/views/admin/wardrobe.yaml
  - !include lovelace/views/admin/attic.yaml
  - !include lovelace/views/admin/outdoor.yaml
  - !include lovelace/views/admin/temperature.yaml
  - !include lovelace/views/admin/doors_and_windows.yaml
  - !include lovelace/views/admin/batteries.yaml
  - !include lovelace/views/admin/control_room.yaml
