title: Tuwima
views:
  - !include lovelace/views/mobile/main.yaml
  - !include lovelace/views/mobile/kitchen.yaml
  - !include lovelace/views/mobile/living_room.yaml
  - !include lovelace/views/mobile/office.yaml
  - !include lovelace/views/mobile/boiler_house.yaml
  - !include lovelace/views/mobile/garage.yaml
  - !include lovelace/views/mobile/gameroom.yaml
  - !include lovelace/views/mobile/upper_bathroom.yaml
  - !include lovelace/views/mobile/toilet.yaml
  - !include lovelace/views/mobile/bedroom.yaml
  - !include lovelace/views/mobile/kamil_room.yaml
  - !include lovelace/views/mobile/visitors_room.yaml
  - !include lovelace/views/mobile/wardrobe.yaml
  - !include lovelace/views/mobile/attic.yaml
  - !include lovelace/views/mobile/outdoor.yaml
  - !include lovelace/views/mobile/calendar.yaml
  - !include lovelace/views/mobile/doors_and_windows.yaml
  - !include lovelace/views/mobile/batteries.yaml
  - !include lovelace/views/mobile/control_room.yaml
