title: Admin Panel
views:
  - !include lovelace/views/main.yaml
  - !include lovelace/views/kitchen.yaml
  - !include lovelace/views/living_room.yaml
  - !include lovelace/views/office.yaml
  - !include lovelace/views/boiler_house.yaml
  - !include lovelace/views/garage.yaml
  - !include lovelace/views/gameroom.yaml
  - !include lovelace/views/upper_bathroom.yaml
  - !include lovelace/views/toilet.yaml
  - !include lovelace/views/bedroom.yaml
  - !include lovelace/views/kamil_room.yaml
  - !include lovelace/views/visitors_room.yaml
  - !include lovelace/views/wardrobe.yaml
  - !include lovelace/views/attic.yaml
  - !include lovelace/views/outdoor.yaml
  - !include lovelace/views/temperature.yaml
  - !include lovelace/views/doors_and_windows.yaml
  - !include lovelace/views/batteries.yaml
  - !include lovelace/views/control_room.yaml
