# - platform: template
#   sensors:
#     temperature_livingroom:
#       friendly_name: "LivingRoom Temperature"
#       device_class: temperature
#       value_template: >-
#         {{ state_attr("climate.int0000001", "current_temperature") }}
#       unit_of_measurement: "°C"

- platform: template
  sensors:
    temperature_office:
      friendly_name: "Office Temperature"
      device_class: temperature
      value_template: >-
        {{ state_attr("climate.gabinet", "current_temperature") }}
      unit_of_measurement: "°C"

- platform: template
  sensors:
    temperature_gameroom:
      friendly_name: "Gameroom Temperature"
      device_class: temperature
      value_template: >-
        {{ state_attr("climate.int0000003", "current_temperature") }}
      unit_of_measurement: "°C"

- platform: template
  sensors:
    temperature_bedroom:
      friendly_name: "Bedroom Temperature"
      device_class: temperature
      value_template: >-
        {{ state_attr("climate.000a1a49a1145f", "current_temperature") }}
      unit_of_measurement: "°C"

- platform: template
  sensors:
    temperature_kamil_room:
      friendly_name: "Kamil Room Temperature"
      device_class: temperature
      value_template: >-
        {{ state_attr("climate.000a1a49a11b83", "current_temperature") }}
      unit_of_measurement: "°C"

- platform: template
  sensors:
    temperature_visitors_room:
      friendly_name: "Visitors Room Temperature"
      device_class: temperature
      value_template: >-
        {{ state_attr("climate.000a18a9a2fc6d", "current_temperature") }}
      unit_of_measurement: "°C"

- platform: template
  sensors:
    heating_mode_office:
      friendly_name: "Heating Mode in Office"
      value_template: >-
        {% if is_state('input_boolean.heating_season', 'on') and not is_state('input_boolean.use_floor_heating_only', 'on') %}
          {% if 
            (
              is_state('input_boolean.is_home_office_mode', 'on') 
              and
              (
                is_state('sensor.home_lifecycle', 'breakfast') 
                or
                is_state('sensor.home_lifecycle', 'work') 
              )
            )
            or
            (
              is_state('binary_sensor.desktop', 'on')
              and
              not is_state('sensor.home_lifecycle', 'sleep')
            )
          %}
            heat
          {% else %}
            standby
          {% endif %}
        {% else %}
          off
        {% endif %}

- platform: template
  sensors:
    heating_mode_livingroom:
      friendly_name: "Heating Mode in Livingroom"
      value_template: >-
        {% if is_state('input_boolean.heating_season', 'on') and not is_state('input_boolean.use_floor_heating_only', 'on') %}
          {% if 
            (
              not is_state('sensor.home_lifecycle', 'work') 
              and
              not is_state('sensor.home_lifecycle', 'bedtime') 
              and
              not is_state('sensor.home_lifecycle', 'sleep') 
            )
          %}
            heat
          {% else %}
            standby
          {% endif %}
        {% else %}
          off
        {% endif %}

- platform: template
  sensors:
    heating_mode_gameroom:
      friendly_name: "Heating Mode in Gameroom"
      value_template: >-
        {% if is_state('input_boolean.heating_season', 'on') and not is_state('input_boolean.use_floor_heating_only', 'on') %}
          {% if 
            (
              is_state('input_boolean.is_gameroom_occupied', 'on') 
              and
              (
                is_state('sensor.home_lifecycle', 'morning') 
                or
                is_state('sensor.home_lifecycle', 'awake') 
                or
                is_state('sensor.home_lifecycle', 'bedtime') 
                or
                is_state('sensor.home_lifecycle', 'sleep') 
              )
            )
          %}
            heat
          {% else %}
            standby
          {% endif %}
        {% else %}
          off
        {% endif %}

- platform: template
  sensors:
    heating_mode_bedroom:
      friendly_name: "Heating Mode in Bedroom"
      value_template: >-
        {% if is_state('input_boolean.heating_season', 'on') and not is_state('input_boolean.use_floor_heating_only', 'on') %}
          {% if 
            (
                is_state('sensor.home_lifecycle', 'morning') 
                or
                is_state('sensor.home_lifecycle', 'awake') 
                or
                is_state('sensor.home_lifecycle', 'bedtime') 
            )
          %}
            heat
          {% elif 
            (
                is_state('sensor.home_lifecycle', 'sleep') 
            )
          %}
            comfort
          {% else %}
            standby
          {% endif %}
        {% else %}
          off
        {% endif %}

- platform: template
  sensors:
    heating_mode_kamil_room:
      friendly_name: "Heating Mode in Kamil Room"
      value_template: >-
        {% if is_state('input_boolean.heating_season', 'on') and not is_state('input_boolean.use_floor_heating_only', 'on') %}
          {% if 
            (
              is_state('input_boolean.is_kamil_room_occupied', 'on') 
              and
              (
                is_state('sensor.home_lifecycle', 'morning') 
                or
                is_state('sensor.home_lifecycle', 'awake') 
                or
                is_state('sensor.home_lifecycle', 'bedtime') 
                or
                is_state('sensor.home_lifecycle', 'sleep') 
              )
            )
          %}
            heat
          {% else %}
            standby
          {% endif %}
        {% else %}
          off
        {% endif %}

- platform: template
  sensors:
    heating_mode_visitors_room:
      friendly_name: "Heating Mode in Visitors Room"
      value_template: >-
        {% if is_state('input_boolean.heating_season', 'on') and not is_state('input_boolean.use_floor_heating_only', 'on') %}
          {% if 
            (
              is_state('input_boolean.is_visitors_room_occupied', 'on') 
              and
              (
                is_state('sensor.home_lifecycle', 'morning') 
                or
                is_state('sensor.home_lifecycle', 'awake') 
                or
                is_state('sensor.home_lifecycle', 'bedtime') 
                or
                is_state('sensor.home_lifecycle', 'sleep') 
              )
            )
          %}
            heat
          {% else %}
            standby
          {% endif %}
        {% else %}
          off
        {% endif %}

- platform: template
  sensors:
    heating_mode_upper_bathroom:
      friendly_name: "Heating Mode in Upper Bathroom"
      value_template: >-
        {% if is_state('input_boolean.heating_season', 'on') and not is_state('input_boolean.use_floor_heating_only', 'on') %}
          {% if 
            (
                is_state('sensor.home_lifecycle', 'morning') 
                or
                is_state('sensor.home_lifecycle', 'awake') 
                or
                is_state('sensor.home_lifecycle', 'relax') 
                or
                is_state('sensor.home_lifecycle', 'bedtime') 
            )
          %}
            heat
          {% else %}
            standby
          {% endif %}
        {% else %}
          off
        {% endif %}

- platform: template
  sensors:
    climate_office_temp_low:
      friendly_name: Climate Office Temperature Low
      value_template: >-
        {% if is_state("sensor.heating_mode_office", "heat") %}
          {{ states("input_number.climate_office_heat_low") }}
        {% elif is_state("sensor.heating_mode_office", "standby") %}
          {{ states("input_number.climate_office_standby_low") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_office_temp_high:
      friendly_name: Climate Office Temperature High
      value_template: >-
        {% if is_state("sensor.heating_mode_office", "heat") %}
          {{ states("input_number.climate_office_heat_high") }}
        {% elif is_state("sensor.heating_mode_office", "standby") %}
          {{ states("input_number.climate_office_standby_high") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_livingroom_temp_low:
      friendly_name: Climate Livingroom Temperature Low
      value_template: >-
        {% if is_state("sensor.heating_mode_livingroom", "heat") %}
          {{ states("input_number.climate_livingroom_heat_low") }}
        {% elif is_state("sensor.heating_mode_livingroom", "standby") %}
          {{ states("input_number.climate_livingroom_standby_low") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_livingroom_temp_high:
      friendly_name: Climate Livingroom Temperature High
      value_template: >-
        {% if is_state("sensor.heating_mode_livingroom", "heat") %}
          {{ states("input_number.climate_livingroom_heat_high") }}
        {% elif is_state("sensor.heating_mode_livingroom", "standby") %}
          {{ states("input_number.climate_livingroom_standby_high") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_gameroom_temp_low:
      friendly_name: Climate Gameroom Temperature Low
      value_template: >-
        {% if is_state("sensor.heating_mode_gameroom", "heat") %}
          {{ states("input_number.climate_gameroom_heat_low") }}
        {% elif is_state("sensor.heating_mode_gameroom", "standby") %}
          {{ states("input_number.climate_gameroom_standby_low") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_gameroom_temp_high:
      friendly_name: Climate Gameroom Temperature High
      value_template: >-
        {% if is_state("sensor.heating_mode_gameroom", "heat") %}
          {{ states("input_number.climate_gameroom_heat_high") }}
        {% elif is_state("sensor.heating_mode_gameroom", "standby") %}
          {{ states("input_number.climate_gameroom_standby_high") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_bedroom_temp_low:
      friendly_name: Climate Bedroom Temperature Low
      value_template: >-
        {% if is_state("sensor.heating_mode_bedroom", "heat") %}
          {{ states("input_number.climate_bedroom_heat_low") }}
        {% elif is_state("sensor.heating_mode_bedroom", "standby") %}
          {{ states("input_number.climate_bedroom_standby_low") }}
        {% elif is_state("sensor.heating_mode_bedroom", "comfort") %}
          {{ states("input_number.climate_bedroom_comfort_low") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_bedroom_temp_high:
      friendly_name: Climate Bedroom Temperature High
      value_template: >-
        {% if is_state("sensor.heating_mode_bedroom", "heat") %}
          {{ states("input_number.climate_bedroom_heat_high") }}
        {% elif is_state("sensor.heating_mode_bedroom", "standby") %}
          {{ states("input_number.climate_bedroom_standby_high") }}
        {% elif is_state("sensor.heating_mode_bedroom", "comfort") %}
          {{ states("input_number.climate_bedroom_comfort_high") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_kamil_room_temp_low:
      friendly_name: Climate Kamil Room Temperature Low
      value_template: >-
        {% if is_state("sensor.heating_mode_kamil_room", "heat") %}
          {{ states("input_number.climate_kamil_room_heat_low") }}
        {% elif is_state("sensor.heating_mode_kamil_room", "standby") %}
          {{ states("input_number.climate_kamil_room_standby_low") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_kamil_room_temp_high:
      friendly_name: Climate Kamil Room Temperature High
      value_template: >-
        {% if is_state("sensor.heating_mode_kamil_room", "heat") %}
          {{ states("input_number.climate_kamil_room_heat_high") }}
        {% elif is_state("sensor.heating_mode_kamil_room", "standby") %}
          {{ states("input_number.climate_kamil_room_standby_high") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_visitors_room_temp_low:
      friendly_name: Climate Visitors Room Temperature Low
      value_template: >-
        {% if is_state("sensor.heating_mode_visitors_room", "heat") %}
          {{ states("input_number.climate_visitors_room_heat_low") }}
        {% elif is_state("sensor.heating_mode_visitors_room", "standby") %}
          {{ states("input_number.climate_visitors_room_standby_low") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_visitors_room_temp_high:
      friendly_name: Climate Visitors Room Temperature High
      value_template: >-
        {% if is_state("sensor.heating_mode_visitors_room", "heat") %}
          {{ states("input_number.climate_visitors_room_heat_high") }}
        {% elif is_state("sensor.heating_mode_visitors_room", "standby") %}
          {{ states("input_number.climate_visitors_room_standby_high") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_upper_bathroom_temp_low:
      friendly_name: Climate Upper Bathroom Temperature Low
      value_template: >-
        {% if is_state("sensor.heating_mode_upper_bathroom", "heat") %}
          {{ states("input_number.climate_upper_bathroom_heat_low") }}
        {% elif is_state("sensor.heating_mode_upper_bathroom", "standby") %}
          {{ states("input_number.climate_upper_bathroom_standby_low") }}
        {% else %}
          5
        {% endif %}

- platform: template
  sensors:
    climate_upper_bathroom_temp_high:
      friendly_name: Climate Upper Bathroom Temperature High
      value_template: >-
        {% if is_state("sensor.heating_mode_upper_bathroom", "heat") %}
          {{ states("input_number.climate_upper_bathroom_heat_high") }}
        {% elif is_state("sensor.heating_mode_upper_bathroom", "standby") %}
          {{ states("input_number.climate_upper_bathroom_standby_high") }}
        {% else %}
          5
        {% endif %}
