- platform: template
  sensors:
    is_home_occupied:
      friendly_name: Is Home Occupied
      value_template: >-
        {{
          is_state('binary_sensor.is_krzysiek_home', 'on')
          or
          is_state('binary_sensor.is_anetka_home', 'on')
          or
          is_state('input_boolean.is_guest_mode', 'on')
        }}
      icon_template: >
        {% if is_state('binary_sensor.is_home_occupied', 'on') %}
          mdi:home-account
        {% else %}
          mdi:home-outline
        {% endif %}

- platform: template
  sensors:
    day_off_mode:
      friendly_name: Day Off Mode
      value_template: >-
        {{
          is_state('binary_sensor.workday_sensor', 'off')
          or
          is_state('input_boolean.is_day_off_mode', 'on')
        }}

- platform: template
  sensors:
    bedtime_mode:
      friendly_name: Is Bedtime
      value_template: "off"

- platform: template
  sensors:
    home_temperature:
      friendly_name: Home Temperature
      device_class: cold
      value_template: >-
        {% if 
          (
            is_state("sensor.heating_mode_office", "heat") 
            and 
            state_attr("climate.gabinet", "current_temperature") < states('input_number.climate_office_heat_low') | float
          )
          or
          (
            is_state("sensor.heating_mode_office", "standby") 
            and 
            state_attr("climate.gabinet", "current_temperature") < states('input_number.climate_office_standby_low') | float
          )
          or
          (
            is_state("sensor.heating_mode_livingroom", "heat") 
            and 
            state_attr("climate.int0000001", "current_temperature") < states('input_number.climate_livingroom_heat_low') | float 
          )
          or
          (
            is_state("sensor.heating_mode_livingroom", "standby") 
            and 
            state_attr("climate.int0000001", "current_temperature") < states('input_number.climate_livingroom_standby_low') | float
          )
          or
          (
            is_state("sensor.heating_mode_gameroom", "heat") 
            and 
            state_attr("climate.int0000003", "current_temperature") < states('input_number.climate_gameroom_heat_low') | float
          )
          or
          (
            is_state("sensor.heating_mode_gameroom", "standby") 
            and 
            state_attr("climate.int0000003", "current_temperature") < states('input_number.climate_gameroom_standby_low') | float
          )
          or
          (
            is_state("sensor.heating_mode_bedroom", "heat") 
            and 
            state_attr("climate.000a1a49a1145f", "current_temperature") < states('input_number.climate_bedroom_heat_low') | float 
          )
          or
          (
            is_state("sensor.heating_mode_bedroom", "standby") 
            and 
            state_attr("climate.000a1a49a1145f", "current_temperature") < states('input_number.climate_bedroom_standby_low') | float
          )
          or
          (
            is_state("sensor.heating_mode_kamil_room", "heat") 
            and 
            state_attr("climate.000a1a49a11b83", "current_temperature") < states('input_number.climate_kamil_room_heat_low') | float 
          )
          or
          (
            is_state("sensor.heating_mode_kamil_room", "standby") 
            and 
            state_attr("climate.000a1a49a11b83", "current_temperature") < states('input_number.climate_kamil_room_standby_low') | float
          )
          or
          (
            is_state("sensor.heating_mode_visitors_room", "heat") 
            and 
            state_attr("climate.000a18a9a2fc6d", "current_temperature") < states('input_number.climate_visitors_room_heat_low') | float 
          )
          or
          (
            is_state("sensor.heating_mode_visitors_room", "standby") 
            and 
            state_attr("climate.000a18a9a2fc6d", "current_temperature") < states('input_number.climate_visitors_room_standby_low') | float
          )
        %}
          on
        {% elif 
          (
            is_state("sensor.heating_mode_office", "heat") 
            and 
            state_attr("climate.gabinet", "current_temperature") > states('input_number.climate_office_heat_high') | float
          )
          and
          (
            is_state("sensor.heating_mode_office", "standby") 
            and 
            state_attr("climate.gabinet", "current_temperature") > states('input_number.climate_office_standby_high') | float
          )
          and
          (
            is_state("sensor.heating_mode_livingroom", "heat") 
            and 
            state_attr("climate.int0000001", "current_temperature") > states('input_number.climate_livingroom_heat_high') | float 
          )
          and
          (
            is_state("sensor.heating_mode_livingroom", "standby") 
            and 
            state_attr("climate.int0000001", "current_temperature") > states('input_number.climate_livingroom_standby_high') | float
          )
          and
          (
            is_state("sensor.heating_mode_gameroom", "heat") 
            and 
            state_attr("climate.int0000003", "current_temperature") > states('input_number.climate_gameroom_heat_high') | float
          )
          and
          (
            is_state("sensor.heating_mode_gameroom", "standby") 
            and 
            state_attr("climate.int0000003", "current_temperature") > states('input_number.climate_gameroom_standby_high') | float
          )
          and
          (
            is_state("sensor.heating_mode_bedroom", "heat") 
            and 
            state_attr("climate.000a1a49a1145f", "current_temperature") > states('input_number.climate_bedroom_heat_high') | float 
          )
          and
          (
            is_state("sensor.heating_mode_bedroom", "standby") 
            and 
            state_attr("climate.000a1a49a1145f", "current_temperature") > states('input_number.climate_bedroom_standby_high') | float
          )
          and
          (
            is_state("sensor.heating_mode_kamil_room", "heat") 
            and 
            state_attr("climate.000a1a49a11b83", "current_temperature") > states('input_number.climate_kamil_room_heat_high') | float 
          )
          and
          (
            is_state("sensor.heating_mode_kamil_room", "standby") 
            and 
            state_attr("climate.000a1a49a11b83", "current_temperature") > states('input_number.climate_kamil_room_standby_high') | float
          )
          and
          (
            is_state("sensor.heating_mode_visitors_room", "heat") 
            and 
            state_attr("climate.000a18a9a2fc6d", "current_temperature") > states('input_number.climate_visitors_room_heat_high') | float 
          )
          and
          (
            is_state("sensor.heating_mode_visitors_room", "standby") 
            and 
            state_attr("climate.000a18a9a2fc6d", "current_temperature") > states('input_number.climate_visitors_room_standby_high') | float
          )
        %}
          off
        {% endif %}
