- platform: ping
  name: desktop
  host: 192.168.1.125
  count: 3
  scan_interval: 60
- platform: ping
  name: laptop_pc
  host: 192.168.1.179
  count: 3
  scan_interval: 60
- platform: ping
  name: samsung_a10
  host: 192.168.1.210
  count: 3
  scan_interval: 60
- platform: ping
  name: mi_10
  host: 192.168.1.78
  count: 3
  scan_interval: 60
- platform: ping
  name: tv_salon
  host: 192.168.1.127
  count: 3
  scan_interval: 60
