- id: "1601646532061"
  alias: Turn On Back Corridor Light when Someone In
  description: ""
  trigger:
    - type: motion
      platform: device
      device_id: 0f5fbe4604aa11eb88fb33327735e82b
      entity_id: binary_sensor.0x00158d0005317a91_occupancy
      domain: binary_sensor
    - type: motion
      platform: device
      device_id: 5bd0557604a911eb8619afa07127780e
      entity_id: binary_sensor.0xec1bbdfffee23cb0_occupancy
      domain: binary_sensor
  condition: []
  action:
    - type: turn_on
      device_id: 9b30703504ab11eb88cb917b08b09f19
      entity_id: switch.0xbc33acfffe4c4d6b_switch
      domain: switch
    - delay: 00:02:00
    - type: turn_off
      device_id: 9b30703504ab11eb88cb917b08b09f19
      entity_id: switch.0xbc33acfffe4c4d6b_switch
      domain: switch
  mode: restart

- alias: Turn On Water Pump on Week Schedule
  trigger:
    - platform: time
      at: "07:00:00"
    - platform: time
      at: "15:50:00"
    - platform: time
      at: "19:00:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    type: turn_on
    device_id: ddb29c81048d11eb80237bf808abce29
    entity_id: switch.water_pump_switch
    domain: switch

- alias: Turn On Water Pump on Saturday Schedule
  trigger:
    - platform: time
      at: "08:00:00"
  condition:
    condition: time
    weekday:
      - sat
  action:
    type: turn_on
    device_id: ddb29c81048d11eb80237bf808abce29
    entity_id: switch.water_pump_switch
    domain: switch

- alias: Turn On Water Pump on Sunday Schedule
  trigger:
    - platform: time
      at: "08:30:00"
    - platform: time
      at: "19:00:00"
  condition:
    condition: time
    weekday:
      - sun
  action:
    type: turn_on
    device_id: ddb29c81048d11eb80237bf808abce29
    entity_id: switch.water_pump_switch
    domain: switch

- alias: Turn Off Water Pump on Week Schedule
  trigger:
    - platform: time
      at: "08:15:00"
    - platform: time
      at: "17:15:00"
    - platform: time
      at: "23:59:59"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    type: turn_off
    device_id: ddb29c81048d11eb80237bf808abce29
    entity_id: switch.water_pump_switch
    domain: switch

- alias: Turn Off Water Pump on Saturday Schedule
  trigger:
    - platform: time
      at: "23:59:59"
  condition:
    condition: time
    weekday:
      - sat
  action:
    type: turn_off
    device_id: ddb29c81048d11eb80237bf808abce29
    entity_id: switch.water_pump_switch
    domain: switch

- alias: Turn Off Water Pump on Sunday Schedule
  trigger:
    - platform: time
      at: "10:30:00"
    - platform: time
      at: "23:59:59"
  condition:
    condition: time
    weekday:
      - sun
  action:
    type: turn_off
    device_id: ddb29c81048d11eb80237bf808abce29
    entity_id: switch.water_pump_switch
    domain: switch
