- alias: Set Temperature for Heat in Office
  trigger:
    platform: state
    entity_id: sensor.heating_mode_office
    to: "heat"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.gabinet
      temperature: 20
      target_temp_high: 21
      target_temp_low: 19
      hvac_mode: heat

- alias: Set Temperature for Standby in Office
  trigger:
    platform: state
    entity_id: sensor.heating_mode_office
    to: "standby"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.gabinet
      temperature: 17
      target_temp_high: 18
      target_temp_low: 16
      hvac_mode: heat

- alias: Set Temperature for Off in Office
  trigger:
    platform: state
    entity_id: sensor.heating_mode_office
    to: "off"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.gabinet
      temperature: 5
      target_temp_high: 5
      target_temp_low: 5
      hvac_mode: off

- alias: Set Temperature for Heat in Livingroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_livingroom
    to: "heat"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.int0000001
      temperature: 20
      target_temp_high: 21
      target_temp_low: 19
      hvac_mode: heat

- alias: Set Temperature for Standby in Livingroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_livingroom
    to: "standby"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.int0000001
      temperature: 17
      target_temp_high: 18
      target_temp_low: 16
      hvac_mode: heat

- alias: Set Temperature for Off in Livingroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_livingroom
    to: "off"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.int0000001
      temperature: 5
      target_temp_high: 5
      target_temp_low: 5
      hvac_mode: off

- alias: Set Temperature for Heat in Gameroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_gameroom
    to: "heat"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.int0000003
      temperature: 22
      target_temp_high: 23
      target_temp_low: 21
      hvac_mode: heat

- alias: Set Temperature for Standby in Gameroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_gameroom
    to: "standby"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.int0000003
      temperature: 19
      target_temp_high: 20
      target_temp_low: 18
      hvac_mode: heat

- alias: Set Temperature for Off in Gameroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_gameroom
    to: "off"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.int0000003
      temperature: 5
      target_temp_high: 5
      target_temp_low: 5
      hvac_mode: off

- alias: Set Temperature for Heat in Bedroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_bedroom
    to: "heat"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a1a49a1145f
      temperature: 20
      target_temp_high: 21
      target_temp_low: 19
      hvac_mode: heat

- alias: Set Temperature for Standby in Bedroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_bedroom
    to: "standby"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a1a49a1145f
      temperature: 17
      target_temp_high: 18
      target_temp_low: 16
      hvac_mode: heat

- alias: Set Temperature for Off in Bedroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_bedroom
    to: "off"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a1a49a1145f
      temperature: 5
      target_temp_high: 5
      target_temp_low: 5
      hvac_mode: off

- alias: Set Temperature for Heat in Kamil Room
  trigger:
    platform: state
    entity_id: sensor.heating_mode_kamil_room
    to: "heat"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a1a49a11b83
      temperature: 20
      target_temp_high: 21
      target_temp_low: 19
      hvac_mode: heat

- alias: Set Temperature for Standby in Kamil Room
  trigger:
    platform: state
    entity_id: sensor.heating_mode_kamil_room
    to: "standby"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a1a49a11b83
      temperature: 17
      target_temp_high: 18
      target_temp_low: 16
      hvac_mode: heat

- alias: Set Temperature for Off in Kamil Room
  trigger:
    platform: state
    entity_id: sensor.heating_mode_kamil_room
    to: "off"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a1a49a11b83
      temperature: 5
      target_temp_high: 5
      target_temp_low: 5
      hvac_mode: off

- alias: Set Temperature for Heat in Visitors Room
  trigger:
    platform: state
    entity_id: sensor.heating_mode_visitors_room
    to: "heat"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a18a9a2fc6d
      temperature: 20
      target_temp_high: 21
      target_temp_low: 19
      hvac_mode: heat

- alias: Set Temperature for Standby in Visitors Room
  trigger:
    platform: state
    entity_id: sensor.heating_mode_visitors_room
    to: "standby"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a18a9a2fc6d
      temperature: 17
      target_temp_high: 18
      target_temp_low: 16
      hvac_mode: heat

- alias: Set Temperature for Off in Visitors Room
  trigger:
    platform: state
    entity_id: sensor.heating_mode_visitors_room
    to: "off"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a18a9a2fc6d
      temperature: 5
      target_temp_high: 5
      target_temp_low: 5
      hvac_mode: off

- alias: Turn On Radiator for Heat in Upper Bathroom
  trigger:
    - platform: numeric_state
      entity_id: sensor.0x086bd7fffef07ec0_temperature
      below: 21
    - platform: state
      entity_id: sensor.heating_mode_upper_bathroom
      to: "heat"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.heating_mode_upper_bathroom
        state: "heat"
      - condition: numeric_state
        entity_id: sensor.0x086bd7fffef07ec0_temperature
        below: 21
  action:
    service: switch.turn_on
    entity_id: switch.upper_bathroom_radiator_switch

- alias: Turn Off Radiator for Heat in Upper Bathroom
  trigger:
    - platform: numeric_state
      entity_id: sensor.0x086bd7fffef07ec0_temperature
      above: 22
    - platform: state
      entity_id: sensor.heating_mode_upper_bathroom
      to: "heat"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.heating_mode_upper_bathroom
        state: "heat"
      - condition: numeric_state
        entity_id: sensor.0x086bd7fffef07ec0_temperature
        above: 22
  action:
    service: switch.turn_off
    entity_id: switch.upper_bathroom_radiator_switch

- alias: Turn On Radiator for Standby in Upper Bathroom
  trigger:
    - platform: numeric_state
      entity_id: sensor.0x086bd7fffef07ec0_temperature
      below: 17
    - platform: state
      entity_id: sensor.heating_mode_upper_bathroom
      to: "standby"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.heating_mode_upper_bathroom
        state: "standby"
      - condition: numeric_state
        entity_id: sensor.0x086bd7fffef07ec0_temperature
        below: 17
  action:
    service: switch.turn_on
    entity_id: switch.upper_bathroom_radiator_switch

- alias: Turn Off Radiator for Standby in Upper Bathroom
  trigger:
    - platform: numeric_state
      entity_id: sensor.0x086bd7fffef07ec0_temperature
      above: 18
    - platform: state
      entity_id: sensor.heating_mode_upper_bathroom
      to: "standby"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.heating_mode_upper_bathroom
        state: "standby"
      - condition: numeric_state
        entity_id: sensor.0x086bd7fffef07ec0_temperature
        above: 18
  action:
    service: switch.turn_off
    entity_id: switch.upper_bathroom_radiator_switch

- alias: Turn On Gas Stove If Any Thermostat Needs This
  trigger:
    platform: state
    entity_id: binary_sensor.home_temperature
    to: "on" # for device_class cold this means "cold"
  action:
    entity_id: switch.tasmota_tasmota # Gas Stove Switch
    service: switch.turn_on

- alias: Turn Off Gas Stove If No Thermostat Needs This
  trigger:
    platform: state
    entity_id: binary_sensor.home_temperature
    to: "off" # for device_class cold this means "normal"
  action:
    entity_id: switch.tasmota_tasmota # Gas Stove Switch
    service: switch.turn_off
