- alias: Set Temperature for Heat in Office
  trigger:
    platform: state
    entity_id: sensor.heating_mode_office
    to: "heat"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.gabinet
      temperature: "{{ states('input_number.climate_office_heat_comfort') | float }}"

- alias: Set Temperature for Standby in Office
  trigger:
    platform: state
    entity_id: sensor.heating_mode_office
    to: "standby"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.gabinet
      temperature: "{{ states('input_number.climate_office_standby_comfort') | float }}"

- alias: Set Temperature for Off in Office
  trigger:
    platform: state
    entity_id: sensor.heating_mode_office
    to: "off"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.gabinet
      temperature: 5

- alias: Set Temperature for Heat in Livingroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_livingroom
    to: "heat"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.int0000001
      temperature: "{{ states('input_number.climate_livingroom_heat_comfort') | float }}"

- alias: Set Temperature for Standby in Livingroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_livingroom
    to: "standby"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.int0000001
      temperature: "{{ states('input_number.climate_livingroom_standby_comfort') | float }}"

- alias: Set Temperature for Off in Livingroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_livingroom
    to: "off"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.int0000001
      temperature: 5

- alias: Set Temperature for Heat in Gameroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_gameroom
    to: "heat"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.int0000003
      temperature: "{{ states('input_number.climate_gameroom_heat_comfort') | float }}"

- alias: Set Temperature for Standby in Gameroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_gameroom
    to: "standby"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.int0000003
      temperature: "{{ states('input_number.climate_gameroom_standby_comfort') | float }}"

- alias: Set Temperature for Off in Gameroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_gameroom
    to: "off"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.int0000003
      temperature: 5

- alias: Set Temperature for Heat in Bedroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_bedroom
    to: "heat"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a1a49a1145f
      temperature: "{{ states('input_number.climate_bedroom_heat_comfort') | float }}"

- alias: Set Temperature for Standby in Bedroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_bedroom
    to: "standby"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a1a49a1145f
      temperature: "{{ states('input_number.climate_bedroom_standby_comfort') | float }}"

- alias: Set Temperature for Off in Bedroom
  trigger:
    platform: state
    entity_id: sensor.heating_mode_bedroom
    to: "off"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a1a49a1145f
      temperature: 5

- alias: Set Temperature for Heat in Kamil Room
  trigger:
    platform: state
    entity_id: sensor.heating_mode_kamil_room
    to: "heat"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a1a49a11b83
      temperature: "{{ states('input_number.climate_kamil_room_heat_comfort') | float }}"

- alias: Set Temperature for Standby in Kamil Room
  trigger:
    platform: state
    entity_id: sensor.heating_mode_kamil_room
    to: "standby"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a1a49a11b83
      temperature: "{{ states('input_number.climate_kamil_room_standby_comfort') | float }}"

- alias: Set Temperature for Off in Kamil Room
  trigger:
    platform: state
    entity_id: sensor.heating_mode_kamil_room
    to: "off"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a1a49a11b83
      temperature: 5

- alias: Set Temperature for Heat in Visitors Room
  trigger:
    platform: state
    entity_id: sensor.heating_mode_visitors_room
    to: "heat"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a18a9a2fc6d
      temperature: "{{ states('input_number.climate_visitors_room_heat_comfort') | float }}"

- alias: Set Temperature for Standby in Visitors Room
  trigger:
    platform: state
    entity_id: sensor.heating_mode_visitors_room
    to: "standby"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a18a9a2fc6d
      temperature: "{{ states('input_number.climate_visitors_room_standby_comfort') | float }}"

- alias: Set Temperature for Off in Visitors Room
  trigger:
    platform: state
    entity_id: sensor.heating_mode_visitors_room
    to: "off"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.000a18a9a2fc6d
      temperature: 5
