- alias: Toggle Office Desk Light
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/Office Desk Light Switch/click
    payload: single
  action:
    service: light.toggle
    entity_id: light.0x588e81fffe4d34ed_light
  mode: single

- alias: Turn On Office Desk Light on 50%
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/Office Desk Light Switch/click
    payload: double
  action:
    service: light.turn_on
    data:
      entity_id: light.0x588e81fffe4d34ed_light
      brightness_pct: 50
  mode: single

- alias: Turn On Office Desk Light on 100%
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/Office Desk Light Switch/click
    payload: triple
  action:
    service: light.turn_on
    data:
      entity_id: light.0x588e81fffe4d34ed_light
      brightness_pct: 100
  mode: single
