- alias: Toggle Outdoor Front Lights
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/Outdoor Lights Switch/action
    payload: 3_single
  action:
    entity_id: switch.0x60a423fffe94f80c_switch_left
    service: switch.toggle
  mode: single

- alias: Toggle Outdoor Side Lights
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/Outdoor Lights Switch/action
    payload: 2_single
  action:
    entity_id: switch.0x60a423fffe9770a3_switch_left
    service: switch.toggle
  mode: single

- alias: Toggle Outdoor Back Lights
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/Outdoor Lights Switch/action
    payload: 1_single
  action:
    entity_id: switch.0x842e14fffedfbfb3_switch_left
    service: switch.toggle
  mode: single
