- alias: Heat Up Upper Bathroom during bath time
  trigger:
    platform: numeric_state
    entity_id: sensor.0x086bd7fffef07ec0_temperature
    below: 21
  condition:
    condition: or
    conditions:
      - condition: time
        after: "06:00:00"
        before: "09:00:00"
      - condition: time
        after: "19:00:00"
        before: "23:30:00"
  action:
    type: turn_on
    device_id: 96015779048f11ebb4c83f96dccde4e4
    entity_id: switch.upper_bathroom_radiator_switch
    domain: switch

- alias: Turn Off Upper Bathroom Radiator during bath time
  trigger:
    platform: numeric_state
    entity_id: sensor.0x086bd7fffef07ec0_temperature
    above: 21.5
  condition:
    condition: or
    conditions:
      - condition: time
        after: "06:00:00"
        before: "09:00:00"
      - condition: time
        after: "19:00:00"
        before: "23:30:00"
  action:
    type: turn_off
    device_id: 96015779048f11ebb4c83f96dccde4e4
    entity_id: switch.upper_bathroom_radiator_switch
    domain: switch

- alias: Heat Up Upper Bathroom beyond bath time
  trigger:
    platform: numeric_state
    entity_id: sensor.0x086bd7fffef07ec0_temperature
    below: 17
  condition:
    condition: or
    conditions:
      - condition: time
        after: "09:00:00"
        before: "19:00:00"
      - condition: time
        after: "23:30:00"
        before: "09:00:00"
  action:
    type: turn_on
    device_id: 96015779048f11ebb4c83f96dccde4e4
    entity_id: switch.upper_bathroom_radiator_switch
    domain: switch

- alias: Turn Off Upper Bathroom Radiator beyond bath time
  trigger:
    platform: numeric_state
    entity_id: sensor.0x086bd7fffef07ec0_temperature
    above: 17.5
  condition:
    condition: or
    conditions:
      - condition: time
        after: "09:00:00"
        before: "19:00:00"
      - condition: time
        after: "23:30:00"
        before: "09:00:00"
  action:
    type: turn_off
    device_id: 96015779048f11ebb4c83f96dccde4e4
    entity_id: switch.upper_bathroom_radiator_switch
    domain: switch
